import type { Metadata } from "next";
import { Bitter, Roboto_Slab } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const robotoSlab = Roboto_Slab({
  weight: ["400", "700"],
  subsets: ["latin", "vietnamese"],
});

export const bitter = Bitter({
  weight: ["400", "700"],
  subsets: ["latin", "vietnamese"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${robotoSlab.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col overflow-hidden">
        {children}
      </body>
    </html>
  );
}
